### ISSUE TITLE
Tests missing

### ISSUE THREAD

**Issue by Jasmine-ge** [timeplus-io/timeplus-native-jdbc#44]
**Test to add:**
Basic:
- [x]   - Date32 
- [x]   - enum8
- [x]   - enum16 

Complex:
  - Array 
- [x]   nullable
- [x]     string
- [x]     date
- [x]     decimal
- [x]     enum
- [x]     float
- [x]     ipv4/ipv6

-   Map

- [x]     nullable
- [x]     fixed_string
- [x]     date
- [x]     decimal
- [x]     enum
- [x]     float
- [x]     ipv4/ipv6

-   Tuple

- [x]     nullable
- [x]     string
- [x]      date
- [x]      decimal
- [x]      enum
- [x]      float
- [x]      ipv4/ipv6

-   LowCardinality

- [x]      nullable

-   Nullable

- [x]      int
- [x]      string
- [x]      date
- [x]      decimal
- [x]      enum
- [x]      float
- [x]      ipv4/ipv6
-   Nested Types
- [x]      Array(LowCardinality), Tuple(LowCardinality), Map(LowCardinality)
- [x]      Tuple(Map), Map(Tuple), Array(Map), Map(Array)

**Comment by yl-lisen** [comment]
update status of the finished sub tasks
